# security-tools/bandit-config.yml
# This profile will be used by Bandit for static code analysis.
# We are defining a baseline profile to fail on any issue found.

# A list of test IDs to skip, here we are not skipping any.
skips: []

# A list of paths to exclude from scanning.
exclude_dirs: ["./tests"]

confidence: "LOW"